### PR TITLE
Randomize assignees

### PR DESCRIPTION
**Pull request by nguyengiabk**
Address #15

### CODE REVIEW

**Comment by pozil** [comment]
Hi @nguyengiabk, thanks for the contribution.
I would like to avoid introducing breaking changes in the action so can you do the following:
- make `numOfAssignee` optional
- if `numOfAssignee` is not provided, keep the original action behavior (use all assignees)

**Comment by nguyengiabk** [comment]
@pozil 
Thanks for review. Will do.

**Comment by nguyengiabk** [comment]
Hi @pozil 
I made it optional.
Please take a look 🙇

**Comment by pozil** [comment]
Looking great, thanks @nguyengiabk. I'll release a new version with your contribution.

**Pull request merged**
